# Generated by Django 3.2.6 on 2021-09-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetespod',
            name='node',
            field=models.CharField(default='', max_length=254),
        ),
    ]
