# Generated by Django 3.2.6 on 2021-09-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210922_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetesservice',
            name='type',
            field=models.CharField(default='', max_length=500),
        ),
    ]
